language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - mysql
  - redis

before_script:
  - "mysql -e 'create database open_rest_es6_boilerplate;'"

node_js:
  - "6"
  - "7"
  - "8"

after_success:
  - codecov
